#!/usr/bin/env sh
test -f "$1" || { printf '%s\n' "Error: Input file missing."; exit 1; };
printf '%s\n' "char $2_name[13] = {\"$(basename $1)\"};"
if [ -x /bin/coffwrap ]; then
	coffwrap -t -n _$2 $1 $2.o
	printf '%s\n' "extern unsigned char $2[];"
	ls -l $1 | read -u a b c d size rest
	printf '%s\n' "int $2_size = $size;"
else
	printf '%s\n' "unsigned char $2[] = {"
	(od -bv || od -ab) < $1 2> /dev/null |
		tr  '\011' '\040' |
		sed  -e 's/^[0-7]*//' -e '/^$/d' -e 's/^[ ]*/0/' -e 's/[ ]*$//' |
		sed  -e 's/ /, 0/g' -e 's/$/,/' -e '$s/,$//' -e 's/^/	/'
	printf '%s\n' "};"
	printf '%s\n' "int $2_size = sizeof $2;"
fi
