#!/usr/bin/env sh
# shellcheck disable=SC2211,SC2046,SC2059,SC2086,SC2015,SC2154

set -e 2> /dev/null || \
	true :

OEXT="${1}" && \
	export OEXT

EXSCR=$(mktemp) || {
	printf '%s\n' \
	"Error: mktemp failed."
	exit 1
}

PROWS=$(printf "%s" "${ROWS:-24}" | \
	sed 's/./& /g') || {
	printf '%s\n' \
	"Error: Failed to set ROWS."
	exit 1
}

PCOLS=$(printf "%s" "${COLS:-80}" | \
	sed 's/./& /g') || {
	printf '%s\n' \
	"Error: Failed to set COLS."
	exit 1
}

printf \
	'#!/usr/bin/env expect\n\
	set timeout 5\n\
	cd ./mince80\n\
	spawn ../ccom'"${OEXT:-}"' config.com\n\
	expect "Would you like to exit and change disks? "\n\
	sleep 0.1;\n\
	send -- "N"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "2\\r\\n"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "9\\r\\n"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "5\\r\\n"\n\
	expect " Any changes? "\n\
	sleep 0.1;\n\
	send -- "Y"\n\
	expect " Which item? "\n\
	sleep 0.1;\n\
	send -- "1\\r\\n"\n' \
	> "${EXSCR:?}" && \

printf \
	'%s\n' \
	'expect "Number of rows on your terminal? (default = 24) "' \
	>> "${EXSCR:?}" && \

printf \
	'sleep 0.1;\n\
	send -- "%s"\n' ${PROWS} \
	>> "${EXSCR:?}" && \

printf \
	'%s\n' \
	"sleep 0.1;"\
	'send -- "\r\n"' \
	>> "${EXSCR:?}" && \

printf \
	'%s\n' \
	'expect "Number of columns on your terminal? (default = 80) "' \
	>> "${EXSCR:?}" && \

printf \
	'sleep 0.1;\n\
	send -- "%s"\n' ${PCOLS} \
	>> "${EXSCR:?}" && \

printf \
	'%s\n' \
	"sleep 0.1;" \
	'send -- "\r\n"' \
	>> "${EXSCR:?}" && \

printf \
	'expect "Any changes?"\n\
	sleep 0.1;\n\
	send -- "N"\n\
	expect "Any changes?"\n\
	sleep 0.1;\n\
	send -- "N"\n\
	expect "Any changes?"\n\
	sleep 0.1;\n\
	send -- "N"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "4"\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "2"\n\
	sleep 0.1;\n\
	send -- "4"\n\
	sleep 0.1;\n\
	send -- "8"\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect "default = "\n\
	sleep 0.1;\n\
	send -- "\\r\\n"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "7\\r\\n"\n\
	expect "?"\n\
	sleep 0.1\n\
	send -- "\\r\\n"\n\
	expect "swp"\n\
	sleep 0.1;\n\
	send -- "Y"\n\
	expect " --> "\n\
	sleep 0.1;\n\
	send -- "8\\r\\n"\n\
	sleep 0.1;\n\
	expect eof;\n' \
	>> "${EXSCR:?}";
	chmod +x "${EXSCR:?}" || \
	true :;

test -f "${EXSCR:?}" && \
	/usr/bin/env expect "${EXSCR:?}" || {
	printf \
		'%s\n' \
		"Error: Expect session failed."
	${RM} "${EXSCR:?}"
	exit 1
}

${RM} "${EXSCR:?}"
