/*
			-----------------------------
			| Other Ascii Control Codes |
			-----------------------------
*/
#define CTLA 1 			/* control a */
#define CTLB 2 			/* control b */
#define CTLC 3 			/* control c */
#define CTLD 4 			/* control d */
#define CTLE 5 			/* control e */
#define CTLF 6 			/* control f */
#define CTLN 14			/* control n */
#define CTLO 15			/* control o */
#define CTLP 16			/* control p */
#define CTLR 18			/* control r */
#define CTLS 19			/* control s */
#define CTLT 20			/* control t */
#define CTLU 21			/* control u */
#define CTLV 22			/* control v */
#define CTLW 23			/* control w */
#define CTLY 25			/* control y */
#define CTLZ 26			/* control z */

