/*
 *      General Data Base Files 
 */
#define DBFILE "database"      /* File containing data base */
#define HTABFILE "hashtab"    /* File containing direcory */

/*
 *      Mail System Files 
 */
#define MAILFRMFILE "mailform.sav"	/* File containing mail formats */
#define MFRMDSCFILE "mformdsc.sav"	/* File containing mail format 
					   descriptions */
/*
 *       List System Files 
 */
#define LISTFRMFILE "listform.sav"	/* File for list formats */
#define LFRMDSCFILE "lformdsc.sav" 	/* File for format descriptions */

/*
 *        Subset System Files 
 */
#define SSFILE "ss.sav"	    /* File used to save subset def's */
#define SSLISTFILE "sslist.sav" /* File used to save subset list */
#define SSDESCFILE "ssdesc.sav" /* File used to save subset descriptors */
 
/*
 *      Serial NUmber File
 */
#define SERIALFILE "serial.sav"
